cart/urls.py
from django.urls import path , include
from .views import cart_detail , cart_add , cart_remove

app_name = 'cart'

urlpatterns = [
    
    path('' , cart_detail, name='cart_details'),
    path('add/<int:product_id>/' , cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('digi/', include('digi.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digi/urls.py
from django.urls import path , include
from . import views

app_name = 'digi'

urlpatterns = [
    
    path('' , views.home_page , name='Home'),
    # path('posts' , views.PostPage.as_view() , name='posts'),
    path('<int:pk>/', views.detail_post , name='detail'),
    path('posts/', views.post_page , name='posts'),
    # path('contact/', views.Contact.as_view() , name='contact'),
    # path('comment/<int:pk>', views.ContactComment.as_view() , name='comment'),
    # path('<int:pk>/edit/', views.PostForm.as_view() , name='edit'),
    # path('<int:pk>/delete/', views.DeletePost.as_view() , name='delete '),
    # path('about/', views.About.as_view() , name='about'),
]

shop/urls.py
from django.urls import path , include
from . import views


app_name = 'shop'

urlpatterns = [
    
    path('' , views.ShopPage.as_view(), name='shop'),
    path('<int:pk>/' , views.BuyProducts.as_view(), name='detail_shop'),
    path('checkout/' , views.Checkout.as_view(), name='checkout'),
    path('order/' , views.Order.as_view(), name='order'),
]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from accounts.models import User

class Product(models.Model): 
    
    price = models.DecimalField(max_digits=10, decimal_places=0)
    name = models.CharField(max_length=50)
    image = models.ImageField()
    category = models.ManyToManyField('SubCategory')
    status = models.BooleanField(default=False)
    quantity = models.IntegerField(null=True , blank=True)

    def __str__(self):
        return self.name
    

class MainCategory(models.Model):
    
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name

class SubCategory(models.Model):
    main_category =models.ForeignKey(MainCategory , on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name    
    
    
    
class Order(models.Model):
    
    customer = models.ForeignKey(User , on_delete=models.CASCADE)
    order_data = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.id
    
class OrderItem(models.Model):    
    order = models.ForeignKey(Order, on_delete=models.CASCADE)        
    product = models.ForeignKey(Product ,null=True , on_delete=models.SET_NULL)
    product_price = models.DecimalField(max_digits=10, decimal_places=0)
    product_cast = models.DecimalField(max_digits=10, decimal_places=0)
    product_count = models.PositiveIntegerField()
    
    def __str__(self):
        return self.id
    
class Invoice(models.Model):    
    order = models.ForeignKey(Order,null=True , on_delete=models.SET_NULL)        
    invoice_data = models.DateField(auto_now_add=True)
    Authority = models.CharField( max_length=200 , blank=True , null=True)

    def __str__(self):
        return self.id
class Transaction(models.Model): 
    
    STATUS_CHOICES = (
        
        ('pending' , 'Pending'),
        ('failed' , 'Failed'),
        ('completed' , 'Completed'),
        
    )  
    
    invoice = models.ForeignKey(Invoice, null=True ,on_delete=models.SET_NULL) 
    transaction_data = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=0)
    status = models.CharField(max_length=10 , choices=STATUS_CHOICES , default='pending')
    
    def __str__(self):
        return self.id

cart/forms.py
from django import forms


PRODUCT_COUNT_CHOICES = [( i , str(i)) for i in range(1 , 6)]

class CartAddProductForm(forms.Form):

    product_count = forms.TypedChoiceField(choices=PRODUCT_COUNT_CHOICES ,
                                           coerce=int)
    
    update = forms.BooleanField(required=False , 
                                initial=False,
                                widget=forms.HiddenInput)
    
        
    

cart/views.py
from django.shortcuts import render , get_object_or_404 , redirect 
from .cart import Cart
from shop.models import Product
from django.urls import reverse
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm



@require_POST 
def cart_add (request , product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid(): 
        form_data = form.cleaned_data
        cart.add(product=product, 
                 product_count=form_data['product_count'],
                 update_count=form_data['update'])
        
    return redirect(reverse('cart:cart_details'))


def cart_detail(request):
    
    cart = Cart(request)
    for item in cart:
        item['update_product_count_form'] = CartAddProductForm(
            initial={
                'product_count' : item['product_count'] , 
                'update' : True
            }
        )
    context = {'cart' : cart}
    return render(request , 'cart.html' , context)

def cart_remove(request , product_id):
    
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect(reverse('cart:cart_details'))

shop/views.py
from django.shortcuts import render ,get_object_or_404
from django.views.generic import TemplateView , UpdateView, CreateView, ListView , DeleteView , DetailView , FormView
from .models import Product , SubCategory ,Order
from cart.forms import CartAddProductForm
from cart.cart import Cart
from decimal import Decimal
from . import models
from django.views import View
from zeep import Client

class ShopPage(ListView):
    
    model = Product
    context_object_name = "products"
    template_name = 'shop.html'
    paginate_by = 6
    
    
    
class BuyProducts(ListView , DetailView , DeleteView):    

    model = Product
    context_object_name = "products"
    template_name = 'single-product.html'
        
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['cart_form'] = CartAddProductForm()
        return context
 
    
class Checkout(View):
    template_name = 'checkout.html'
    context_object_name = 'cart_items'

    def get_queryset(self):
        cart = Cart(self.request)
        for item in cart:
            item['update_product_count_form'] = CartAddProductForm(
                initial={
                    'product_count': item['product_count'],
                    'update': True
                }
            )
        return cart        
            

    def get(self, request, *args, **kwargs):
        cart = Cart(request)
        return render(request, self.template_name, {'cart': cart})

    def post(self, request, *args, **kwargs):
        cart = Cart(request)
        order = models.Order.objects.create(customer=request.user)
        for item in cart:
            models.OrderItem.objects.create(
                order=order,
                product=item['product'],
                product_price=item['price'],
                product_count=item['product_count'],
                product_cost=Decimal(item['product_count']) * Decimal(item['price'])
            )
        # order.customer = request.user
        # order.save()
        cart.clear()
        return render(request, 'order_detail.html', {'order': order})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        return context
      
      
class Order(ListView):
    
    model = Order
    template_name = 'order_detail.html'
    context_object_name = 'order'
          
          
class to_bank(ListView):
    
    def get_queryset(self , request , order_id):
        
        order = get_object_or_404(models.Order , id=order_id)
        amount = 0
        order_items = models.OrderItem.objects.filter(order=order)
        
        for item in order_items: 
            amount += item.product_cast
            
        client = Client('https://www.zarinpal.com/pg/webGate/wsdl') 
        callback_url = 'http://http://127.0.0.1:8000/callback/'
        mobile = ''
        email = ''
        description = 'test'
        merchant = '**********************'
        result = client.service.PaymentRequest(merchant , amount , mobile, description , callback_url )
        
        if result.Status == 100 and len(result.Authority)==36:   
            pass      
    
    
    
    
      

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Responsive Bootstrap4 Shop Template, Created by Imran Hossain from https://imransdesign.com/">

	<!-- title -->
	<title>Fruitkha</title>

	<!-- favicon -->
	<link rel="shortcut icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
	<!-- google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
	<!-- fontawesome -->
	<link rel="stylesheet" href="{% static 'assets/css/all.min.css' %}">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<!-- owl carousel -->
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
	<!-- magnific popup -->
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<!-- animate css -->
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<!-- mean menu css -->
	<link rel="stylesheet" href="{% static 'assets/css/meanmenu.min.css' %}">
	<!-- main style -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- responsive -->
	<link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">

</head>
<body>
	
	<!--PreLoader-->
    <div class="loader">
        <div class="loader-inner">
            <div class="circle"></div>
        </div>
    </div>
    <!--PreLoader Ends-->
	
	<!-- header -->
	<div class="top-header-area" id="sticker">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-sm-12 text-center">
					<div class="main-menu-wrap">
						<!-- logo -->
						<div class="site-logo">
							<a href="index.html">
								<img src="{% static 'assets/img/logo.png' %}" alt="">
							</a>
						</div>
						<!-- logo -->

						<!-- menu start -->
						<nav class="main-menu">
							<ul>
								<li class="current-list-item"><a href="{% url "digi:Home" %}">Home</a>
								</li>
								<li><a href="#">About</a></li>
								
								{% comment %} <li><a href="#">Pages</a>
									<ul class="sub-menu">
										<li><a href="404.html">404 page</a></li>
										<li><a href="about.html">About</a></li>
										<li><a href="cart.html">Cart</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="#">Contact</a></li>
										<li><a href="{% url "digi:posts" %}">Post</a></li>
										<li><a href="{% url "shop:shop" %}">Shop</a></li>
									</ul>
								</li> {% endcomment %}
								<li><a href="{% url "digi:posts" %}">Post</a></li>
								<li><a href="#">Contact</a></li>
								<li><a href="#">Shop</a>
									<ul class="sub-menu">
										<li><a href="{% url "shop:shop" %}">Shop</a></li>
										<li><a href="checkout.html">Check Out</a></li>
										<li><a href="single-product.html">Single Product</a></li>
										<li><a href="{% url "cart:cart_details" %}">Cart</a></li>
									</ul>
								</li>
								<li>
									<div class="header-icons">
										<a> 
											{% with total_item=cart|length %}
        										{% if total_item > 0 %}
													<small>Your cart:<a href="{% url 'cart:cart_details' %}"> {{ total_item}} item(s)  </a></small>
												{% else %}
													<p>Your cart is empty.</p>
												{% endif %}
											{% endwith %}
										</a>
										<a class="mobile-hide search-bar-icon" href="#"><i class="fas fa-search"></i></a>
									</div>
								</li>
							</ul>
						</nav>
						<a class="mobile-show search-bar-icon" href="#"><i class="fas fa-search"></i></a>
						<div class="mobile-menu"></div>
						<!-- menu end -->
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end header -->

{% block context %}


{% endblock context %}


	<!-- footer -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="footer-box about-widget">
						<h2 class="widget-title">About us</h2>
						<p>Ut enim ad minim veniam perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box get-in-touch">
						<h2 class="widget-title">Get in Touch</h2>
						<ul>
							<li>34/8, East Hukupara, Gifirtok, Sadan.</li>
							<li>support@fruitkha.com</li>
							<li>+00 111 222 3333</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box pages">
						<h2 class="widget-title">Pages</h2>
						<ul>
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="services.html">Shop</a></li>
							<li><a href="news.html">News</a></li>
							<li><a href="contact.html">Contact</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="footer-box subscribe">
						<h2 class="widget-title">Subscribe</h2>
						<p>Subscribe to our mailing list to get the latest updates.</p>
						<form action="index.html">
							<input type="email" placeholder="Email">
							<button type="submit"><i class="fas fa-paper-plane"></i></button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end footer -->
	
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<p>Copyrights &copy; 2019 - <a href="https://imransdesign.com/">Imran Hossain</a>,  All Rights Reserved.</p>
				</div>
				<div class="col-lg-6 text-right col-md-12">
					<div class="social-icons">
						<ul>
							<li><a href="#" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-linkedin"></i></a></li>
							<li><a href="#" target="_blank"><i class="fab fa-dribbble"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end copyright -->
	
	<!-- jquery -->
	<script src="{% static 'assets/js/jquery-1.11.3.min.js' %}"></script>
	<!-- bootstrap -->
	<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<!-- count down -->
	<script src="{% static 'assets/js/jquery.countdown.js' %}"></script>
	<!-- isotope -->
	<script src="{% static 'assets/js/jquery.isotope-3.0.6.min.js' %}"></script>
	<!-- waypoints -->
	<script src="{% static 'assets/js/waypoints.js' %}"></script>
	<!-- owl carousel -->
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<!-- magnific popup -->
	<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
	<!-- mean menu -->
	<script src="{% static 'assets/js/jquery.meanmenu.min.js' %}"></script>
	<!-- sticker js -->
	<script src="{% static 'assets/js/sticker.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block context %}
	

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Fresh and Organic</p>
						<h1>Cart</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->
	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>
									<th class="product-image">Product Image</th>
									<th class="product-name">Name</th>
									<th class="product-price">Price</th>
									<th class="product-quantity">Quantity</th>
									<th class="product-total">Total</th>
								</tr>
							</thead>
							<tbody>
								{% for item in cart %}
									{% with product=item.product %}
										<tr class="table-body-row">
											<td class="product-remove"><a href="{% url "cart:cart_remove" product.id %}"><i class="far fa-window-close"></i></a></td>
											<td class="product-image"><img src="{{ product.image.url }}" alt=""></td>
											<td class="product-name">{{ product.name }}</td>
											<td class="product-price">${{ item.price }}</td>
											<td> 
												<form method="post" action="{% url "cart:cart_add" product.id %}">
													{{ item.update_product_count_form.product_count}}
													{{ item.update_product_count_form.update}}
													{% csrf_token %}
													<input type="submit" value="Update">
												</form>
											</td> 
											<td class="product-total">{{item.total_price}} </td>
										</tr>
									{% endwith%}
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>Total</th>
									<th>Price</th>
								</tr>
							</thead>
							<tbody>
								<tr class="total-data">
									<td><strong>Subtotal: </strong></td>
									<td>-</td>
								</tr>
								<tr class="total-data">
									<td><strong>Shipping: </strong></td>
									<td>-</td>
								</tr>
								<tr class="total-data">
									<td><strong>Total: </strong></td>
									<td>$ {{cart.get_total_price}} </td>
								</tr>
							</tbody>
						</table>
						<div class="cart-buttons">
							<a href="cart.html" class="boxed-btn">Update Cart</a>
							<a href="{% url "shop:checkout" %}" class="boxed-btn black">Check Out</a>
						</div>
					</div>

					<div class="coupon-section">
						<h3>Apply Coupon</h3>
						<div class="coupon-form-wrap">
							<form action="index.html">
								<p><input type="text" placeholder="Coupon"></p>
								<p><input type="submit" value="Apply"></p>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end cart -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->


{% endblock context %}

templates/posts.html
{% extends "base.html" %}
{% load static %}
{% block context %}

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Organic Information</p>
						<h1>News Article</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->
<div class="latest-news-bg news-bg-1"></div>
	<!-- latest news -->
	<div class="latest-news mt-150 mb-150">
		<div class="container">
			<div class="row">
				{% for posts in posts %}

					<div class="col-lg-5 col-md-8">
						<div class="single-latest-news">
							<div class="product-image">
								<a href="single-product.html"><img src="{{ posts.image.url }}" alt=""></a>
							</div>
							<div class="news-text-box">
								<h3><a href="single-news.html">{{ posts.title }}.</a></h3>
								<p class="blog-meta">
									<span class="author"><i class="fas fa-user"></i> {{ posts.author.get_full_name }}</span>
			
									<span class="date"><i class="fas fa-calendar"></i>{{ posts.published_date|date:'M - Y' }}</span>
								</p>
								<p class="excerpt">{{ posts.content }}</p>
								<a href="{% url "digi:detail" posts.id %}" class="read-more-btn">read more <i class="fas fa-angle-right"></i></a>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>

			<div class="row">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 text-center">
							<div class="pagination-wrap">
								<ul>
									<li><a href="#">Prev</a></li>
									<li><a href="#">1</a></li>
									<li><a class="active" href="#">2</a></li>
									<li><a href="#">3</a></li>
									<li><a href="#">Next</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end latest news -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

{% endblock context %}	

templates/shop.html
{% extends "base.html" %}
{% load static %}
{% block context %}

	<!-- search area -->
	<div class="search-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<span class="close-btn"><i class="fas fa-window-close"></i></span>
					<div class="search-bar">
						<div class="search-bar-tablecell">
							<h3>Search For:</h3>
							<input type="text" placeholder="Keywords">
							<button type="submit">Search <i class="fas fa-search"></i></button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end search arewa -->
	
	<!-- breadcrumb-section -->
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>Fresh and Organic</p>
						<h1>Shop</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- products -->
	<div class="product-section mt-150 mb-150">
		<div class="container">

			<div class="row">
                <div class="col-md-12">
                    <div class="product-filters">
                        <ul>
                            <li class="active" data-filter="*">All</li>
                            <li data-filter=".strawberry">Strawberry</li>
                            <li data-filter=".berry">Berry</li>
                            <li data-filter=".lemon">Lemon</li>
                        </ul>
                    </div>
                </div>
            </div>

			<div class="row product-lists">
				{% for products in products %}
					<div class="col-lg-4 col-md-6 text-center strawberry">
						<div class="single-product-item">
							<div class="product-image">
								<a href="single-product.html"><img src={{ products.image.url }} alt=""></a>
							</div>
							<h3>{{ products.name }}</h3>
							<p class="product-price"><span>Available in stock : {{ products.quantity }}</span> {{ products.price }}$ </p>
							{% comment %} <a method='post' action='{% url 'cart:cart_add' products.id %}' type='submit' value='Add To Cart'> Add To Cart </a> {% endcomment %}
							<a href="{% url 'shop:detail_shop' products.id %}"  class="cart-btn"><i class="fas fa-shopping-cart"></i> About Product</a>
						</div>
					</div>
				{% endfor %}
			</div>

			<div class="row">
				<div class="col-lg-12 text-center">
					<div class="pagination-wrap">
						<ul>
							<li><a href="#">Prev</a></li>
							<li><a href="#">1</a></li>
							<li><a class="active" href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">Next</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end products -->

	<!-- logo carousel -->
	<div class="logo-carousel-section">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="logo-carousel-inner">
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/1.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/2.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/3.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/4.png' %}" alt="">
						</div>
						<div class="single-logo-item">
							<img src="{% static 'assets/img/company-logos/5.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end logo carousel -->

{% endblock context %}